### ISSUE TITLE
Bluebird Dependency

### ISSUE THREAD

**Issue by joshrivers** [mrgamer/express-raml-store#4]
Hey, looks like bluebird was added to package.json as a dev-dependency rather than a production dependency, and I think it's needed at runtime. Can you take a peek?

**Comment by colthreepv** [comment]
Sure, my mistake, the idea was to make it a dev dependency to use bluebird only for debugging purposes.

i'm refactoring the code to not require it at all, since functionality is covered by native Promises

**Comment by joshrivers** [comment]
I'm still crashing with 

  Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/riversj/vagrant/boot2docker/zipwhip-apispec/editor-dock/node_modules/express-raml-store/api.js:6:28)

on Node v0.12.5

**Comment by colthreepv** [comment]
mmm Indeed, I read up that node 0.12.x had native promises always enabled, anyway native promises are not a good choice for any serious module, since [they have memory leaks](https://github.com/tj/co/issues/180)

I'll make bluebird a must and just get over with it.

**Comment by colthreepv** [comment]
Really thanks for your patience, Josh
